// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WOTeUHAVO-SqKFqmUepWUa_DNWAdPuQ',
    appId: '1:331583731427:web:9034c6e16f67e8e7a537d6',
    messagingSenderId: '331583731427',
    projectId: 'finally-44261',
    authDomain: 'finally-44261.firebaseapp.com',
    storageBucket: 'finally-44261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8h9_SoLBhONNsEtXlG0IxdlQENHn1W0k',
    appId: '1:331583731427:android:01b95f0f97625e88a537d6',
    messagingSenderId: '331583731427',
    projectId: 'finally-44261',
    storageBucket: 'finally-44261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUk7TJbjK2Wxe7Kqk7txqYSPTDPUND52U',
    appId: '1:331583731427:ios:91a8492dfd88f6aba537d6',
    messagingSenderId: '331583731427',
    projectId: 'finally-44261',
    storageBucket: 'finally-44261.appspot.com',
    iosClientId: '331583731427-k7bq2e7i7iav92bidb6t9igo0prl7o07.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
